apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Values.namespace }}
  name: nginx-service
spec:
  selector:
    app: nginx
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetport: {{ .Values.service.targetport }}
